import {
    HOT_SET_LABEL_0,
    HOT_SET_LABEL_1,
    HOT_SET_LABEL_2,
    HOT_SET_LABEL_3,
    HOT_SET_LABEL_4,
    HOT_SET_LABEL_5,
    HOT_SET_LABEL_6,
    HOT_SET_LABEL_7,
    HOT_SET_LABEL_8,
    HOT_SET_LABEL_9,
    TABSTER_HOT_ACTIVATE_0_COMMAND,
    TABSTER_HOT_ACTIVATE_1_COMMAND,
    TABSTER_HOT_ACTIVATE_2_COMMAND,
    TABSTER_HOT_ACTIVATE_3_COMMAND,
    TABSTER_HOT_ACTIVATE_4_COMMAND,
    TABSTER_HOT_ACTIVATE_5_COMMAND,
    TABSTER_HOT_ACTIVATE_6_COMMAND,
    TABSTER_HOT_ACTIVATE_7_COMMAND,
    TABSTER_HOT_ACTIVATE_8_COMMAND,
    TABSTER_HOT_ACTIVATE_9_COMMAND,
} from "./consts";

export type THotSaveCommand =
    | typeof TABSTER_HOT_ACTIVATE_0_COMMAND
    | typeof TABSTER_HOT_ACTIVATE_1_COMMAND
    | typeof TABSTER_HOT_ACTIVATE_2_COMMAND
    | typeof TABSTER_HOT_ACTIVATE_3_COMMAND
    | typeof TABSTER_HOT_ACTIVATE_4_COMMAND
    | typeof TABSTER_HOT_ACTIVATE_5_COMMAND
    | typeof TABSTER_HOT_ACTIVATE_6_COMMAND
    | typeof TABSTER_HOT_ACTIVATE_7_COMMAND
    | typeof TABSTER_HOT_ACTIVATE_8_COMMAND
    | typeof TABSTER_HOT_ACTIVATE_9_COMMAND;

export type THotLabel =
    | typeof HOT_SET_LABEL_0
    | typeof HOT_SET_LABEL_1
    | typeof HOT_SET_LABEL_2
    | typeof HOT_SET_LABEL_3
    | typeof HOT_SET_LABEL_4
    | typeof HOT_SET_LABEL_5
    | typeof HOT_SET_LABEL_6
    | typeof HOT_SET_LABEL_7
    | typeof HOT_SET_LABEL_8
    | typeof HOT_SET_LABEL_9;
